version: '3.8'

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    container_name: vue-frontend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend-dev

  backend-dev:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    container_name: yii-backend-dev
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=yii2db
      - DB_USER=yiiuser
      - DB_PASSWORD=yiipass

  mysql:
      image: mysql:8.0
      container_name: mysql-db
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: yii2db
        MYSQL_USER: yiiuser
        MYSQL_PASSWORD: yiipass
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_ROOT_HOST: '%'          # 允许root从任何主机访问
      command: 
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - mysql_data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:

